- client/modules/i18n/startup.js
> check cookie first to detemine language

- imports/plugins/included/email-templates/server/mutations/renderEmail.js
> fix: remove shopid destructure and use data.shopid

- imports/plugins/core/inventory/server/no-meteor/utils/startup.js
Resolves: Changes logic to determine  isLowQuantity for catalog product.
> feat: modify logic how we decide isLowQuantity

- imports/plugins/core/inventory/server/no-meteor/utils/publishProductToCatalog.js
Resolves: Modify logic how we set isLowQuantity when publishing product.
> feat: modify logic for isLowQuantity when publishing products

- imports/plugins/core/orders/server/no-meteor/mutations/placeOrder.js
Adds functionality to include functions of type "customOrderValidation" for validation purposes.
> feat: add custom validation via customOrderValidation functions

- imports/plugins/core/accounts/server/methods/inviteShopMember.js
- imports/plugins/core/accounts/server/methods/inviteShopOwner.js
- imports/plugins/core/orders/server/no-meteor/mutations/sendOrderEmail.js
Resolves #463
Disables unused emails
> fix: disable unused emails

- imports/plugins/core/email/server/no-meteor/mutations/sendEmail.js
- imports/plugins/core/orders/server/no-meteor/util/getDataForOrderEmail.js
> feat: Update mailing data for Santander

- imports/plugins/core/catalog/server/no-meteor/utils/publishProductToCatalog.js
Signed-off-by: Jaka Maver <jm18457@gmail.com>
Resolves: Publish product with no variants to catalog
Impact: **minor**  
Type: **feature**
> feat: Publish product to catalog with no variants

- imports/plugins/core/orders/server/no-meteor/util/getDataForOrderEmail.js
Includes cashpresso url into order email data.
> feat: include cashpresso url in email

- imports/plugins/core/accounts/server/methods/sendResetPasswordEmail.js
- imports/plugins/core/accounts/server/util/getDataForEmail.js
- imports/plugins/core/accounts/server/util/sendWelcomeEmail.js
> fix: Email shipping address data and add storefront url

- imports/plugins/core/orders/server/no-meteor/util/getDataForOrderEmail.test.js
Fix test which failed due to modification of getOrderEmail function
> fix: Unit test due to modification of function in previous commits

- .gitignore
- .vscode/launch.json
> feat: Include vscode debug settings to git repository

- imports/plugins/core/orders/server/no-meteor/util/updateGroupTotals.js
> feat: GREEN-60 remove only discount count

- imports/node-app/core-services/cart/mutations/createCart.js
> fix: Moved discountId and renamed newCart to savedCart

- imports/collections/schemas/orders.js
- imports/node-app/core-services/cart/simpleSchemas.js
> fix: Cart and order schema extended

- imports/node-app/core-services/orders/util/updateGroupTotals.js
- package-lock.json
Reapplies commit https://github.com/reactioncommerce/reaction/commit/a136b7038a53b7c85fc50dc8ab647750c3910214 which was lost in merge and change due to change of file path.
> Feat/green 760 update reaction 2.9.0 discount

- imports/node-app/core-services/orders/util/getDataForOrderEmail.test.js
> Updated reaction tests

- imports/collections/extend/productSimple.js
> Extended product simple schema with system priority

- imports/collections/schemas/address.js
- imports/node-app/core-services/cart/simpleSchemas.js
- imports/node-app/core-services/orders/simpleSchemas.js
> feat: added title and honorifics to billing address schema

- imports/collections/schemas/cart.js
- imports/node-app/core-services/cart/simpleSchemas.js
- imports/node-app/core-services/cart/util/addCartItems.js
> feat: add color to cart items

- imports/node-app/plugins/sitemap-generator/startup.js
- package-lock.json
> Removed sitemap jobs generation

- imports/collections/schemas/address.js
- imports/node-app/core-services/cart/simpleSchemas.js
- imports/node-app/core-services/orders/simpleSchemas.js
> feat: Added house number to billing address

- imports/node-app/core-services/catalog/simpleSchemas.js
- imports/node-app/plugins/simple-pricing/util/publishProductToCatalog.js
- imports/node-app/plugins/simple-pricing/util/xformCurrencyExchangePricing.js
- imports/plugins/core/versions/server/util/convertCatalogItem.js
> Prevent saving infinity values to product catalog

- imports/node-app/core-services/orders/util/getDataForOrderEmail.js
> Fixed labels in confirmation email

- imports/collections/extend/productVariant.js
> Extended product variant schema

- imports/node-app/core-services/orders/util/getDataForOrderEmail.js
- package-lock.json
> Added order cancellation notification status

- elasticmq.conf
- imports/collections/schemas/address.js
- imports/collections/schemas/cart.js
- imports/collections/schemas/orders.js
- imports/node-app/core-services/cart/simpleSchemas.js
- imports/node-app/core-services/orders/simpleSchemas.js
- imports/node-app/core-services/orders/util/buildOrderItem.js
- imports/node-app/core-services/orders/util/getDataForOrderEmail.js
- imports/node-app/core-services/orders/util/getDataForOrderEmail.test.js
> Extended schema for hepster insurance

- imports/collections/extend/productSimple.js
- package-lock.json
> feat ASANA-1173600296363561: Add fields isBikeOfMonth and isBikeOfWeek

- imports/collections/schemas/cart.js
- imports/node-app/core-services/cart/simpleSchemas.js
- package-lock.json
> Extended cart schema with dateOfBirth

- imports/node-app/core-services/cart/simpleSchemas.js
- imports/node-app/core-services/cart/util/addCartItems.js
- imports/node-app/core-services/orders/util/getDataForOrderEmail.js
> feat: Add attributes to cart

- imports/node-app/core-services/orders/util/getDataForOrderEmail.js
> fix: Remove code added by mistake

- imports/node-app/core-services/orders/mutations/cancelOrderItem.js
> feat ASANA-1173187643594379: Cancel payment if full order is canceled

- imports/node-app/core-services/account/util/getDataForEmail.js
Removes unused data from emails.
> feat: Remove address 2 from email data

- imports/collections/extend/productSimple.js
- package-lock.json
> Added bike of week/month discount text

- imports/collections/schemas/cart.js
> Added milčeageGroup to cart

- imports/node-app/core-services/orders/util/getDataForOrderEmail.js
> Extend email for presale functionality

- imports/node-app/core-services/orders/util/getDataForOrderEmail.js
> Update condition for presale in email

- imports/node-app/plugins/email-smtp/util/sendSMTPEmail.js
> Added bcc option when sending email

- imports/node-app/core-services/email/mutations/sendEmail.js
> order id reference only if we have order email

- imports/collections/schemas/orders.js
- imports/node-app/core-services/orders/schemas/schema.graphql
- imports/node-app/core-services/orders/simpleSchemas.js
- imports/plugins/core/orders/server/no-meteor/simpleSchemas.js
> Add email reminder in schema

- imports/node-app/core-services/orders/mutations/updateOrder.js
> Email reminder to update order

- imports/collections/schemas/orders.js
- imports/node-app/core-services/orders/mutations/updateOrder.js
- imports/node-app/core-services/orders/schemas/schema.graphql
- imports/node-app/core-services/orders/simpleSchemas.js
- imports/plugins/core/orders/server/no-meteor/simpleSchemas.js
> change emailReminder to boolean

- imports/test-utils/__mocks__/meteor/mongo.js
> Mock modules required by "integrations" plugin

- imports/node-app/core-services/email/mutations/sendEmail.js
> Added template information to jobs

- imports/node-app/core-services/inventory/utils/startup.js
- imports/node-app/plugins/simple-inventory/startup.js
> Revert "Feat/asana 1198216079703581 incorrect inventory"

- imports/node-app/core-services/orders/simpleSchemas.js
- imports/node-app/core-services/orders/util/buildOrderItem.js
> feat: Add product and variant attributes to order item

- imports/node-app/core-services/orders/mutations/addOrderFulfillmentGroup.test.js
- imports/node-app/core-services/orders/mutations/cancelOrderItem.test.js
- imports/node-app/core-services/orders/mutations/moveOrderItems.test.js
- imports/node-app/core-services/orders/mutations/splitOrderItem.test.js
> Skip tests

- imports/node-app/core-services/orders/util/getDataForOrderEmail.js
> feat: Add new field to determine if action is order status cancel
